export const notificationsState: NotificationsState = {
    notifications: []
};

export interface NotificationsState {
    notifications: Array<Notification>;
}

export interface Notification {
    id?: string;
    title: string;
    description: string;
    isRead: boolean;
    notificationInfo: string;
}

export enum NotificationActionTypes {
    SEND_NOTIFICATION = "SEND_NOTIFICATION",
    SEND_NOTIFICATION_SUCCESS = "SEND_NOTIFICATION_SUCCESS",
    SEND_NOTIFICATION_FAILED = "SEND_NOTIFICATION_FAILED",
    MARK_NOTIFICATION_AS_READ = "MARK_NOTIFICATION_AS_READ",
    MARK_NOTIFICATION_AS_READ_SUCCESS = "MARK_NOTIFICATION_AS_READ_SUCCESS",
    MARK_NOTIFICATION_AS_READ_FAILED = "MARK_NOTIFICATION_AS_READ_FAILED",
    RECEIVE_NOTIFICATION = "RECEICE_NOTIFICATION",
    RECEIVE_NOTIFICATION_SUCCESS = "RECEIVE_NOTIFICATION_SUCCESS",
    RECEIVE_NOTIFICATION_FAILED = "RECEIVE_NOTIFICATION_FAILED",
    GET_ALL_USER_NOTIFICATIONS = "GET_ALL_USER_NOTIFICATIONS",
    GET_ALL_USER_NOTIFICATIONS_SUCCESS = "GET_ALL_USER_NOTIFICATIONS_SUCCESS",
    GET_ALL_USER_NOTIFICATIONS_FAILED = "GET_ALL_USER_NOTIFICATIONS_FAILED"
}